<a href="https://colab.research.google.com/github/Saritha-242020/Python/blob/main/Assignment7__Numpy_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd


#1. Create a numpy array containing the numbers from 1 to 10, and then reshape it to a 2x5 matrix.

In [2]:
arr1 = np.arange(1, 11)
reshaped_arr1 = arr1.reshape((2, 5))
print("Matrix:\n", reshaped_arr1)

Matrix:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


#2. Create a numpy array containing the numbers from 1 to 20, and then extract the elements between the 5th and 15th index.


In [3]:
arr2 = np.arange(1, 21)
extracted = arr2[5:16]
print("\nArray:\n", extracted)


Array:
 [ 6  7  8  9 10 11 12 13 14 15 16]


#3. Create a Pandas series with the following data: {'apples': 3, 'bananas': 2, 'oranges': 1}. Then, add a new item to the series with the key 'pears' and the value 4.


In [4]:
fruit_series = pd.Series({'apples': 3, 'bananas': 2, 'oranges': 1})
fruit_series['pears'] = 4
print("\nFruits:\n", fruit_series)


Fruits:
 apples     3
bananas    2
oranges    1
pears      4
dtype: int64


#4. Create a dataframe with the following columns: name, age, and gender. The dataframe should have 10 rows of data.


In [6]:
data = {
    'name': [f'Person{i}' for i in range(1, 11)],
    'age': [25, 30, 22, 40, 35, 28, 33, 26, 31, 29],
    'gender': ['Male', 'Female', 'Male', 'Female', 'Male', 'Female', 'Male', 'Female', 'Male', 'Female']
}
df = pd.DataFrame(data)
print("\nData:\n", df)



Data:
        name  age  gender
0   Person1   25    Male
1   Person2   30  Female
2   Person3   22    Male
3   Person4   40  Female
4   Person5   35    Male
5   Person6   28  Female
6   Person7   33    Male
7   Person8   26  Female
8   Person9   31    Male
9  Person10   29  Female


#5. Add a new column to the data frame created in question 1, called occupation. The values for this column should be Programmer, Manager, and Analyst, corresponding to the rows in the dataframe.


In [8]:
occupations = ['Programmer', 'Manager', 'Analyst', 'Programmer', 'Manager',
               'Analyst', 'Programmer', 'Manager', 'Analyst', 'Programmer']
df['occupation'] = occupations
print("\nPosition\n", df)



Position
        name  age  gender  occupation
0   Person1   25    Male  Programmer
1   Person2   30  Female     Manager
2   Person3   22    Male     Analyst
3   Person4   40  Female  Programmer
4   Person5   35    Male     Manager
5   Person6   28  Female     Analyst
6   Person7   33    Male  Programmer
7   Person8   26  Female     Manager
8   Person9   31    Male     Analyst
9  Person10   29  Female  Programmer


#6.Select the rows of the dataframe where the age is greater than or equal to 30.


In [10]:
age_filtered_df = df[df['age'] >= 30]
print("\nList of people whose age greater than 30:\n", age_filtered_df)


List of people whose age greater than 30:
       name  age  gender  occupation
1  Person2   30  Female     Manager
3  Person4   40  Female  Programmer
4  Person5   35    Male     Manager
6  Person7   33    Male  Programmer
8  Person9   31    Male     Analyst


#7. Convert this dataframe to a csv file and read that csv file, finally display the contents.


In [11]:
csv_path = 'dataframe_output.csv'
df.to_csv(csv_path, index=False)

# Read the CSV file
df_from_csv = pd.read_csv(csv_path)
print("\nCSV file:\n", df_from_csv)



CSV file:
        name  age  gender  occupation
0   Person1   25    Male  Programmer
1   Person2   30  Female     Manager
2   Person3   22    Male     Analyst
3   Person4   40  Female  Programmer
4   Person5   35    Male     Manager
5   Person6   28  Female     Analyst
6   Person7   33    Male  Programmer
7   Person8   26  Female     Manager
8   Person9   31    Male     Analyst
9  Person10   29  Female  Programmer
